project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Formation R"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: 01-aide_memoire_r_sas.qmd
        text: Introduction
      - href: Trucs%20et%20astuces%20en%20R.qmd
        text: "Trucs et astuces"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
